name: Django Github Action

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 2
            matrix:
                python-version: [3.9]

        steps:
            - uses: actions/checkout@v3
            - name: Setup Python Version ${{ matrix.python-version }}
              uses: actions/setup-python@v4.1.0
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Lint with flake8
              run:
                flake8 .
            - name: Running the tests
              run: |
                python manage.py test

    deploy:
      runs-on: ubuntu-latest
      name: deploy our application to heroku
      steps:
        - name: checkout
          uses: actions/checkout@v3

        - name: Deploy
          uses: akhileshns/heroku-deploy@v3.12.14 # This is the action
          with:
              heroku_api_key: ${{secrets.HEROKU_API_KEY}}
              heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
              heroku_email: "ajayagrawal1905@gmail.com"
              branch: "main"

